# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  lint:
    desc: Run linters
    cmds:
      - docker run --rm -v ${PWD}:/app -w /app davidanson/markdownlint-cli2 '**/*.md' --fix
      - docker run --rm --user yamllint -v "$(pwd):/data" contane/yamllint -f colored .
