---
# https://taskfile.dev
version: '3'

vars:
  # Colors
  RED: \033[31m
  GREEN: \033[1;32m
  RESET: \033[0m
  # Directories
  APPS_DIR: apps
  BUILD_DIR: .build
  # Docker images
  YAMLFIX_IMAGE: otherguy/yamlfix:latest
  KUBECONFORM_IMAGE: ghcr.io/yannh/kubeconform:latest
  MARKDOWNLINT_IMAGE: davidanson/markdownlint-cli2:latest
  KUBE_LINTER_IMAGE: stackrox/kube-linter:latest
  PLUTO_IMAGE: us-docker.pkg.dev/fairwinds-ops/oss/pluto:v5
  POLARIS_IMAGE: us-docker.pkg.dev/fairwinds-ops/oss/polaris:10
  YAMLLINT_IMAGE: cytopia/yamllint:latest
  KUBECTL_IMAGE: bitnami/kubectl:latest
  # Computed
  KUSTOMIZATION_DIRS:
    sh: |
      if [ "$OS" = "Windows_NT" ]; then
        powershell -Command 'Get-ChildItem . -Recurse -Include kustomization.yaml,kustomization.yml `
          | ForEach-Object { [System.IO.Path]::GetDirectoryName($_.FullName) }'
      else
        find . -type f \( -name "kustomization.yaml" -o -name "kustomization.yml" \) -exec dirname {}
      fi

tasks:
  default:
    desc: Show available tasks
    cmds: [task --list]
  all:
    cmds:
      - task: spell-check
      - task: lint
      - task: build
      - task: validate
      - cmd: printf "\n{{.GREEN}}✨ All validations passed!{{.RESET}}"
        silent: true
  lint:
    desc: Run linters
    silent: true
    cmds:
      - task: md-fix
      - task: yaml-fix
      - task: yaml-lint
  build:
    desc: Build all resources
    silent: true
    cmds:
      - task: kustomize-build
  validate:
    desc: Validate all resources
    aliases: [valid]
    silent: true
    cmds:
      - task: validate-schema
      - task: kube-lint
      - task: deprecation-check
      - task: polaris
  clean:
    desc: Clean up build directory
    silent: true
    cmds:
      - task: remove-build-dirs
  spell-check:
    aliases: [spell]
    silent: true
    deps: [check-docker]
    desc: Run spell check
    cmds:
      - printf "\n{{.GREEN}}✅ Running spell check...{{.RESET}}\n"
      - docker run --rm -v "{{.ROOT_DIR}}:/data" -w /data ghcr.io/streetsidesoftware/cspell:latest
        --no-progress --color

  # Internal tasks
  check-docker:
    desc: Check if Docker is running
    internal: true
    silent: true
    run: once
    cmds:
      - |
        docker info > /dev/null 2>&1 || {
          printf "\n{{.RED}}❌ Docker is not running. Please start Docker Desktop.{{.RESET}}"
          exit 1
        }
  yaml-fix:
    internal: true
    silent: true
    deps: [check-docker]
    desc: Fix YAML files
    cmds:
      - printf "\n{{.GREEN}}✅ Fixing YAML files...{{.RESET}}\n"
      - docker run --rm -v "{{.ROOT_DIR}}:/workspace" -w /workspace -e YAMLFIX_LINE_LENGTH="80"
        -e YAMLFIX_WHITELINES="0" -e YAMLFIX_COMMENTS_WHITELINES="1" -e YAMLFIX_SECTION_WHITELINES="1"
        {{.YAMLFIX_IMAGE}} .
  md-fix:
    internal: true
    silent: true
    deps: [check-docker]
    desc: Fix Markdown files
    cmds:
      - printf "\n{{.GREEN}}✅ Fixing markdown files...{{.RESET}}\n"
      - docker run --rm -v "{{.ROOT_DIR}}:/app" -w /app {{.MARKDOWNLINT_IMAGE}} '**/*.md'
        --fix
  yaml-lint:
    internal: true
    silent: true
    deps: [check-docker]
    desc: Lint YAML files
    cmds:
      - printf "\n{{.GREEN}}📝 Checking YAML syntax...{{.RESET}}\n"
      - docker run --rm -v "{{.ROOT_DIR}}:/data" {{.YAMLLINT_IMAGE}} -f colored .
  create-build-dirs:
    desc: Create build directory
    internal: true
    silent: true
    run: once
    cmds:
      - for:
          var: KUSTOMIZATION_DIRS
        cmd: |
          if [ "$OS" = "Windows_NT" ]; then
            powershell -Command 'New-Item -Path "{{.ITEM}}/{{.BUILD_DIR}}" -ItemType Directory -Force' > /dev/null 2>&1
          else
            mkdir -p "{{.ITEM}}/{{.BUILD_DIR}}" > /dev/null 2>&1
          fi
  remove-build-dirs:
    desc: Remove build directory
    internal: true
    silent: true
    cmds:
      - for:
          var: KUSTOMIZATION_DIRS
        cmd: |
          if [ "$OS" = "Windows_NT" ]; then
            powershell -Command 'Remove-Item -Path "{{.ITEM}}/{{.BUILD_DIR}}" -Recurse -Force' > /dev/null 2>&1
          else
            rm -rf "{{.ITEM}}/{{.BUILD_DIR}}" > /dev/null 2>&1
          fi
  kustomize-build:
    desc: Build all kustomizations to verify syntax
    internal: true
    silent: true
    run: once
    deps: [check-docker, create-build-dirs]
    cmds:
      - printf "\n{{.GREEN}}🔨 Building kustomizations...{{.RESET}}\n"
      - for:
          var: KUSTOMIZATION_DIRS
        cmd: |-
          docker run --rm \
          -v "{{.ITEM}}:/workspace" \
          -w /workspace \
          {{.KUBECTL_IMAGE}} \
          kustomize . --enable-helm \
          > "{{.ITEM}}/{{.BUILD_DIR}}/deployment.yaml" \
          && printf "✅ Built %s\n" "{{.ITEM}}" \
          || printf "{{.RED}}❌ Failed to build %s{{.RESET}}\n" "{{.ITEM}}"
  validate-schema:
    desc: Validate against Kubernetes schemas with kubeconform
    internal: true
    silent: true
    deps: [kustomize-build]
    cmds:
      - printf "\n{{.GREEN}}✅ Validating Kubernetes schemas...{{.RESET}}\n"
      - for:
          var: KUSTOMIZATION_DIRS
        cmd: |-
          docker run --rm \
          -v "{{.ITEM}}/{{.BUILD_DIR}}:/data" \
          {{.KUBECONFORM_IMAGE}} \
          -summary \
          -schema-location default \
          -schema-location https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json \
          -ignore-missing-schemas \
          /data/deployment.yaml \
          && printf "✅ Validated %s\n" "{{.ITEM}}" \
          || printf "{{.RED}}❌ Failed to validate %s{{.RESET}}\n" "{{.ITEM}}"
  kube-lint:
    desc: Run security and best practice checks with kube-linter
    internal: true
    silent: true
    deps: [kustomize-build]
    cmds:
      - printf "\n{{.GREEN}}🔒 Checking best practices with kube-linter...{{.RESET}}\n"
      - for:
          var: KUSTOMIZATION_DIRS
        cmd: |-
          docker run --rm \
          -v "{{.ITEM}}/{{.BUILD_DIR}}:/data" \
          {{.KUBE_LINTER_IMAGE}} \
          lint \
          /data/deployment.yaml \
          && printf "✅ Validated %s\n" "{{.ITEM}}" \
          || printf "{{.RED}}❌ Failed to validate %s{{.RESET}}\n" "{{.ITEM}}"
  deprecation-check:
    desc: Check for deprecated Kubernetes APIs with pluto
    internal: true
    silent: true
    deps: [kustomize-build]
    cmds:
      - printf "\n{{.GREEN}}🔒 Checking deprecated APIs...{{.RESET}}\n"
      - for:
          var: KUSTOMIZATION_DIRS
        cmd: |-
          docker run --rm \
          -v "{{.ITEM}}/{{.BUILD_DIR}}:/data" \
          {{.PLUTO_IMAGE}} \
          detect \
          /data/deployment.yaml \
          && printf "✅ Validated %s\n" "{{.ITEM}}" \
          || printf "{{.RED}}❌ Failed to validate %s{{.RESET}}\n" "{{.ITEM}}"
  polaris:
    desc: Run security and best practice checks with polaris
    internal: true
    silent: true
    deps: [kustomize-build]
    cmds:
      - printf "\n{{.GREEN}}🔒 Checking best practices with polaris...{{.RESET}}\n"
      - for:
          var: KUSTOMIZATION_DIRS
        cmd: |-
          docker run --rm \
          -v "{{.ITEM}}/{{.BUILD_DIR}}:/data" \
          -v ".config:/config" \
          {{.POLARIS_IMAGE}} \
          polaris audit \
          --audit-path /data \
          --config /config/polaris.yaml \
          --format pretty \
          --only-show-failed-tests true \
          && printf "✅ Validated %s\n" "{{.ITEM}}" \
          || printf "{{.RED}}❌ Failed to validate %s{{.RESET}}\n" "{{.ITEM}}"
