---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - cluster-secret-store.yaml
  - smb-creds.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 2.4.1
    releaseName: external-secrets
    namespace: external-secrets
    includeCRDs: true
    valuesFile: ./values.yaml

patches:
  - target:
      kind: Deployment
      name: bitwarden-sdk-server
      namespace: external-secrets
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: bitwarden-sdk-server
      spec:
        template:
          spec:
            automountServiceAccountToken: false
            securityContext:
              seccompProfile:
                type: RuntimeDefault
            containers:
              - name: bitwarden-sdk-server
                securityContext:
                  allowPrivilegeEscalation: false
                  runAsNonRoot: true
                  runAsUser: 65532
                  capabilities:
                    drop: [ALL]
