---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opencost

resources:
  - namespace.yaml
  - networkpolicy.yaml

helmCharts:
  - name: opencost
    repo: https://opencost.github.io/opencost-helm-chart/
    version: 2.5.32
    releaseName: opencost
    namespace: opencost
    includeCRDs: false
    valuesFile: values.yaml
