---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-photos-ro
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-csi-synology-photos-ro
  resources:
    requests:
      storage: 50Gi
