---
apiVersion: v1
kind: Service
metadata:
  name: photoprism
  namespace: photoprism
spec:
  ports:
    - port: 80
      targetPort: 2342
      protocol: TCP
      name: http
  selector:
    app: photoprism
