persistence:
  config:
    enabled: false
  originals:
    enabled: true
    existingClaim: pvc-photos-ro
    mountPath: /photoprism/originals
    # Required by chart library: specify access mode and requested size
    accessMode: ReadWriteMany
    size: 50Gi
  import:
    enabled: false
  backup:
    enabled: false

mariadb:
  enabled: false
