apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photoprism
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mkoelle/homelab.git
    targetRevision: HEAD
    path: apps/media/photoprism
  destination:
    server: https://kubernetes.default.svc
    namespace: photoprism
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
