---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: filebrowser-gateway
  namespace: filebrowser
spec:
  endpointSelector:
    matchLabels:
      app: filebrowser
  ingress:
    - fromEntities:
        - "ingress"
