---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-photos-ro
  namespace: filebrowser
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: photos-pv
  resources:
    requests:
      storage: 100Gi # Must be less than or equal to PV capacity (1Ti)

