---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: filebrowser-quota
  namespace: filebrowser
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: "512Mi"
    limits.cpu: "2000m"
    limits.memory: "2Gi"
    pods: "5"
