---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core-argocd

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - github.com/argoproj/argo-cd//manifests/cluster-install?ref=v3.3.8

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json

patches:
  - path: patch-deployments.yaml
  - path: patch-statefulsets.yaml
  - path: argocd-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - patch: |
      - op: replace
        path: /rules
        value:
          - apiGroups: ["*"]
            resources: ["*"]
            verbs: [get, list, watch]
          - apiGroups: [""]
            resources: [pods, services, endpoints, configmaps, secrets, namespaces,
              serviceaccounts, events, resourcequotas, podtemplates]
            verbs: [get, list, watch, create, update, patch, delete]
          - apiGroups: [apps]
            resources: [deployments, statefulsets, daemonsets, replicasets]
            verbs: [get, list, watch, create, update, patch, delete]
          - apiGroups: [networking.k8s.io]
            resources: [ingresses, networkpolicies]
            verbs: [get, list, watch, create, update, patch, delete]
          - apiGroups: [rbac.authorization.k8s.io]
            resources: [roles, rolebindings]
            verbs: [get, list, watch, create, update, patch, delete]
          - apiGroups: [rbac.authorization.k8s.io]
            resources: [clusterroles, clusterrolebindings]
            verbs: [get, list, watch]
          - apiGroups: [policy]
            resources: [poddisruptionbudgets]
            verbs: [get, list, watch, create, update, patch, delete]
          - apiGroups: [batch]
            resources: [jobs, cronjobs]
            verbs: [get, list, watch, create, update, patch, delete]
          - apiGroups: [coordination.k8s.io]
            resources: [leases]
            verbs: [get, list, watch, create, update, patch, delete]
          - apiGroups: [argoproj.io]
            resources: [applications, appprojects, applicationsets,
              applicationsets/finalizers, applicationsets/status]
            verbs: [get, list, watch, create, update, patch, delete]
    target:
      kind: ClusterRole
      name: argocd-application-controller
