---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller

spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: argocd-application-controller
          args:
            - --repo-server
            - argocd-repo-server:8081
            - --enable-helm
