---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller

spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: argocd-application-controller
          args:
            - /usr/local/bin/argocd-application-controller
            - --enable-helm
