---
# Static SMB-backed PersistentVolume for Photoprism (managed in core storage)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-photos-ro
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: synology-photos-ro
  csi:
    driver: csi.san.synology.com
    volumeHandle: photoprism-photos-smb-ro
    volumeAttributes:
      protocol: smb
      dsm: asgard.local
      location: /volume1
      source: //asgard.local/photo
    nodeStageSecretRef:
      name: synology-smb-credentials
      namespace: photoprism
