---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: synology-csi-talos
    repo: https://zebernst.github.io/synology-csi-talos
    releaseName: synology-csi-talos
    includeCRDs: true
    namespace: core-synology
    valuesFile: ./values.yaml
