---
# SMB-backed PersistentVolume for read-only photo access
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-photos-smb
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: photos-smb-volume
    volumeAttributes:
      source: "//192.168.1.10/volume1/photo"
    nodeStageSecretRef:
      name: smb-creds
      namespace: photoprism
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-photos-smb
  namespace: photoprism
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: smb
  resources:
    requests:
      storage: 1Ti
