---
# Secret for SMB share credentials
# TODO: Update with actual username and password
apiVersion: v1
kind: Secret
metadata:
  name: smb-creds
  namespace: photoprism
type: Opaque
stringData:
  username: "pod-photos"
  password: "Not-th3-real-password"
