---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos-pv
spec:
  capacity:
    storage: 1Ti # Set to a large default, adjust as needed
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: photos-pv
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: photos-pv
    volumeAttributes:
      source: "//192.168.1.10/photo"
    nodeStageSecretRef:
      name: smb-creds
      namespace: core-secrets
