---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - cilium-networkpolicy.yaml
  - grafana-admin-secret.yaml
  - httproute.yaml

helmCharts:
  - name: victoria-metrics-single
    repo: https://victoriametrics.github.io/helm-charts
    version: 0.42.0
    releaseName: vmsingle
    namespace: monitoring
    includeCRDs: false
    valuesFile: values-vmsingle.yaml
  - name: victoria-metrics-alert
    repo: https://victoriametrics.github.io/helm-charts
    version: 0.44.0
    releaseName: vmalert
    namespace: monitoring
    includeCRDs: false
    valuesFile: values-vmalert.yaml
  - name: kube-state-metrics
    repo: https://prometheus-community.github.io/helm-charts
    version: 7.5.1
    releaseName: kube-state-metrics
    namespace: monitoring
    includeCRDs: false
    valuesFile: values-kube-state-metrics.yaml
  - name: prometheus-node-exporter
    repo: https://prometheus-community.github.io/helm-charts
    version: 4.55.0
    releaseName: node-exporter
    namespace: monitoring
    includeCRDs: false
    valuesFile: values-node-exporter.yaml
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 10.5.15
    releaseName: grafana
    namespace: monitoring
    includeCRDs: false
    valuesFile: values-grafana.yaml
