terraform {
  required_providers {
    zitadel = {
      source  = "zitadel/zitadel"
      version = "1.2.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.35.1"
    }
  }

  # State stored as a Secret in-cluster -- no external state store needed for
  # a single-node homelab. in_cluster_config uses the Job's own ServiceAccount
  # token (see terraform-job.yaml's RBAC).
  backend "kubernetes" {
    secret_suffix     = "zitadel"
    namespace         = "zitadel"
    in_cluster_config = true
  }
}

provider "zitadel" {
  domain = "id.hl.mkoelle.com"
  # PAT auto-generated by the zitadel chart's FirstInstance.Org.Machine.Pat
  # block and written to Secret "terraform-runner-pat" (key "pat") -- mounted
  # into this Job by terraform-job.yaml. Never sourced from Bitwarden: Zitadel
  # generates it itself, so there's nothing to pre-declare.
  #
  # `token` (not `access_token`, which doesn't exist in this provider
  # version -- confirmed against the v1.2.0 source, pinned above) takes a
  # *file path*; the provider reads and trims it itself. Passing file()
  # content directly, as this used to, fails with "Unsupported argument".
  token = "/var/run/secrets/zitadel/pat"
}

provider "kubernetes" {
  host                   = "https://kubernetes.default.svc"
  cluster_ca_certificate = file("/var/run/secrets/kubernetes.io/serviceaccount/ca.crt")
  token                  = file("/var/run/secrets/kubernetes.io/serviceaccount/token")
}
