terraform {
  required_providers {
    zitadel = {
      source = "zitadel/zitadel"
      # 1.2.0 -> 2.12.8: gets us auto_linking on zitadel_org_idp_google
      # (see main.tf), the whole reason for this bump. Deliberately NOT
      # 3.x: v3.0.0 makes user-provided secrets (client_secret here)
      # write-only, which needs Terraform CLI >= 1.11 (terraform-job.yaml
      # pins hashicorp/terraform:1.9.8) and a different HCL syntax
      # (separate _wo/_version attributes) -- out of scope for what this
      # bump is actually for. Verified every resource/data source this repo
      # uses (project, application_oidc, org_idp_google, login_policy,
      # orgs) against the v2.12.8 docs first: all fields we set are
      # unchanged: names, types, and required/optional status all match
      # exactly. Only genuinely new thing is auto_linking itself.
      version = "2.12.8"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.35.1"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.6.3"
    }
  }

  # State stored as a Secret in-cluster -- no external state store needed for
  # a single-node homelab. in_cluster_config uses the Job's own ServiceAccount
  # token (see terraform-job.yaml's RBAC).
  backend "kubernetes" {
    secret_suffix     = "zitadel"
    namespace         = "zitadel"
    in_cluster_config = true
  }
}

provider "zitadel" {
  domain = "id.hl.mkoelle.com"
  # JWT Profile machine key, auto-generated by the zitadel chart's
  # FirstInstance.Org.Machine.MachineKey block and written to Secret
  # "terraform-runner" (key "terraform-runner.json") -- mounted into this
  # Job by terraform-job.yaml. Never sourced from Bitwarden: Zitadel
  # generates it itself, so there's nothing to pre-declare.
  #
  # NOT the sibling terraform-runner-pat Secret: this wants a JWT Profile
  # key file (private key + user ID), not a raw bearer token -- confirmed
  # against the provider source when this was `token` (now the deprecated
  # name for the same argument at v2.12.8; jwt_profile_file is the
  # current name with identical semantics, so just renamed here).
  jwt_profile_file = "/var/run/secrets/zitadel/terraform-runner.json"
}

provider "kubernetes" {
  host                   = "https://kubernetes.default.svc"
  cluster_ca_certificate = file("/var/run/secrets/kubernetes.io/serviceaccount/ca.crt")
  token                  = file("/var/run/secrets/kubernetes.io/serviceaccount/token")
}
