terraform {
  required_providers {
    zitadel = {
      source  = "zitadel/zitadel"
      version = "1.2.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.35.1"
    }
  }

  # State stored as a Secret in-cluster -- no external state store needed for
  # a single-node homelab. in_cluster_config uses the Job's own ServiceAccount
  # token (see terraform-job.yaml's RBAC).
  backend "kubernetes" {
    secret_suffix     = "zitadel"
    namespace         = "zitadel"
    in_cluster_config = true
  }
}

provider "zitadel" {
  domain = "id.hl.mkoelle.com"
  # JWT Profile machine key, auto-generated by the zitadel chart's
  # FirstInstance.Org.Machine.MachineKey block and written to Secret
  # "terraform-runner" (key "terraform-runner.json") -- mounted into this
  # Job by terraform-job.yaml. Never sourced from Bitwarden: Zitadel
  # generates it itself, so there's nothing to pre-declare.
  #
  # NOT the sibling terraform-runner-pat Secret: `token` here doesn't take
  # a raw bearer token at this pinned v1.2.0 -- confirmed against
  # zitadel/helper/client.go at that tag, it routes through
  # middleware.JWTProfileFromPath, i.e. it wants this JWT Profile JSON key
  # file, not a PAT. `access_token` (a real raw-bearer-token argument)
  # doesn't exist until a later provider major version.
  token = "/var/run/secrets/zitadel/terraform-runner.json"
}

provider "kubernetes" {
  host                   = "https://kubernetes.default.svc"
  cluster_ca_certificate = file("/var/run/secrets/kubernetes.io/serviceaccount/ca.crt")
  token                  = file("/var/run/secrets/kubernetes.io/serviceaccount/token")
}
